### ISSUE TITLE
Cake Component - Autoloading

### ISSUE THREAD

**Issue by bzitzow** [uzyn/cakephp-composer#10]
Composers Autoloader is not loading the php components that were downloaded from Composer from within a CakePHP Component - ie:

```
    app/Controller/Component/MyComponent.php
    Fatal error: Class 'ApplePusher' not found in /path/to/cake/app/Controller/Component/MyComponent.php on line 20
```

**Comment by uzyn** [comment]
I don't think that's how Composer is supposed to be used. 

For this to work, I guess you should be loading the component from the main app's composer and not within a component.

**Comment by uzyn** [comment]
I'm closing this issue for it has been without updates for 2 months. If this is still a valid issue, please reopen with more information.
