### ISSUE TITLE
Class 'Composer\Installers\Installer' not found

### ISSUE THREAD

**Issue by wkhatch** [uzyn/cakephp-composer#12]
Following along with the info on installing this plugin into a cakephp project, and when attempting to install the plugins specified in composer.json, via cake composer.c install, getting:

PHP Fatal error:  Class 'Composer\Installers\Installer' not found in phar:///Library/WebServer/Documents/Server-PHP/app/Plugin/Composer/Vendor/Composer/composer.phar/src/Composer/Plugin/PluginManager.php on line 216

**Comment by wilr** [comment]
Try removing the vendor folder in the project.

**Comment by uzyn** [comment]
Closing this issue as it hasn't been updated for awhile. 

Please reopen with new information if this issue is still valid.

**Comment by wkhatch** [comment]
I don't know what I did to resolve this problem when I first hit it, but after deploying this app to a new server, I'm once again hitting it.  I don't have a vendor directory, but I do have a Vendor. I moved it aside, and still same problem.

**Comment by uzyn** [comment]
@wkhatch Delete away Vendor/ and then run composer install.

**Comment by wkhatch** [comment]
I already did that. Don't worry about it; I converted to submodules and am ditching composer. 

Bill

**Comment by tylercollier** [comment]
The solution of removing 'vendor' worked for me. Easy.

**Comment by Oxicode** [comment]
> The solution of removing 'vendor' worked for me. Easy.

+1

**Comment by ndzemaruna** [comment]
This did not work for me

**Comment by pitchandtone** [comment]
Deleting vendor folder worked fine for me.

**Comment by wkhatch** [comment]
once it's included in the project, it seems difficult to remove, so, I ended up revisiting this. Ultimately, I ended up having to delete both Vendor, vendors and, the lock file, then run composer.... install, and everything came back to bubble. 

Bill

**Comment by Laykou** [comment]
Deleting vendor folder worked for me too :+1:

**Comment by Antoniossss** [comment]
Dumping vendor and `composer install` did the trick

**Comment by jilenloa** [comment]
Deleting vendor folder also worked for me

**Comment by SayedShahidi** [comment]
Deleting the vendor folder worked ! +1

**Comment by edutrul** [comment]
$ rm -rf vendor
$ composer clear-cache
$ composer install
Worked for me!!
