### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by dereuromark** [uzyn/cakephp-composer#13]
You should add a composer.json file.
See
https://github.com/electblake/cakephp-composer/compare
and
https://github.com/JacopKane/cakephp-composer/compare

**Comment by uzyn** [comment]
Thanks. Cool. Will do it. 

Aside from convention, just wondering if there are any points to having composer.json here?

**Comment by dereuromark** [comment]
I guess to also download/handle this plugin via composer. Even though doing it manually would probably be just as easy/fast.
