### ISSUE TITLE
Usage of composer for cakephp

### ISSUE THREAD

**Issue by simkimsia** [uzyn/cakephp-composer#6]
Hi Uzyn, 

this is not an issue of your plugin per se. More to do with the use of Composer in a CakePHP app.
## Elaboration below:

I am having some weird issues with `git submodule update` for a Plugin dependency with Jenkins @ CloudBees.

So I am switching some, if not, all my dependencies from `git submodule` to `Composer`.

I came across this repo called `composer installers`. https://github.com/composer/installers

I was wondering how to use this for both Plugin and Vendor dependencies.

I am not familiar with Composer and even after reading the docs, I am uncertain how to say, place this dependency specifically to Plugin/xxx

I know how to do this with `git submodule add`.

So how do I do the same but with Composer or better yet, Composer installers, please advise me.

To make things easier, I want to use 2 actual examples.
- https://github.com/milesj/Utility is to be placed inside my app/Plugin/Utility 
- https://github.com/simkimsia/php-gd-simpleimage is to be placed inside my app/Vendor/SimpleImage

**Comment by uzyn** [comment]
For https://github.com/milesj/Utility you should be able to do it simply be doing requiring milesj/Utility. Just place `composer.json` at `app/` and it should work.

**Comment by simkimsia** [comment]
Hi Uzyn,

how do I enforce the rule that the Plugin will go to the Plugin folder?

What about those that are meant for Vendor folder?

With gratitude,
KimSia
金城

**Comment by uzyn** [comment]
You can't as a consumer. That would have to be decided by the package maintainer.

**Comment by simkimsia** [comment]
Hi U-Zyn,

thank you for your response.

In that case,

1)  how does composer installers play its part in this whole composer
ecosystem?

https://github.com/composer/installers

2) how does one package something for composer and packagist to use?

With gratitude,
KimSia
金城

**Comment by uzyn** [comment]
A package is a plugin or it is not, if a package is not, you can't magically turn it into Wordpress plugin simply by placing it at `wp-plugins` directory for instance. Similarly you cannot do the same by turning any generic PHP package into CakePHP plugin simply by placing it at `app/Plugin/`

If all that you want to do is place all packages into `app/Plugin/` (why?), just set [`vendor-dir`](http://getcomposer.org/doc/04-schema.md#config) to `Plugin`.

**Comment by simkimsia** [comment]
Thank you, U-Zyn.

I will update you once I have any progress.

Cheers!

With gratitude,
KimSia
金城

**Comment by simkimsia** [comment]
Hi U-Zyn, 

I understand the whole Composer situation better now. 

Thank you for your assistance.

My question now is what should I add to .gitignore after I move to using Composer?

Let us use the example of a plugin called cakedc/migrations

When I do a 

`Console/cake composer.c require cakedc/migrations`

I will get the following files and folders.

APP/Plugin/Migrations/
APP/Vendor/autoload.php
APP/Vendor/composer/
APP/composer.json
APP/composer.lock

What should be added and committed to my repo?
What should be ignored?

Thank you.

**Comment by uzyn** [comment]
You add `composer.json` and `composer.lock` into repository. Ignore the rest.

**Comment by simkimsia** [comment]
Thank you!

With gratitude,
KimSia
金城
